application: okinotes
version: 1-0-alpha7
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: dist/img/favicon.ico
  upload: dist/img/favicon.ico
- url: /static
  static_dir: static  
- url: /.*
  script: _go_app